function hangman_game(patternId) {
  
  // variables
  var
    hm_container        = $("#" + patternId), // Full container
    hm_wordContainer      = hm_container.find('.hm__word'),
    hm_word             = '',
    hm_wordArray        = [],
    hm_wordList             = [
  { word: "flaunting", definition: "show off complacently" },
  { word: "apprise", definition: "give notice to inform" },
  { word: "bedizen", definition: "to adorn especially in a cheap showy manner" },
  { word: "valorous", definition: "brave" },
  { word: "nugatory", definition: "trifling/worthless" },
  { word: "affinity", definition: "close connection relationship" },
  { word: "abeyance", definition: "suspended action" },
  { word: "insensible", definition: "unconscious unresponsive unaffected" },
  { word: "turpitude", definition: "wickedness shamefulness" },
  { word: "intransigent", definition: "uncompromising" },
  { word: "wag", definition: "merry person" },
  { word: "specious", definition: "illogical of questionable truth or merit" },
  { word: "reiterate", definition: "say or do again several times" },
  { word: "deter", definition: "discourage hinder" },
  { word: "refulgent", definition: "shining brilliant" },
  { word: "fervor", definition: "warmth of feelings earnestness" },
  { word: "yarn", definition: "tale story fibers for knitting" },
  { word: "palpitate", definition: "tremble beat rapidly and irregularly" },
  { word: "mettle", definition: "quality of endurance or courage" },
  { word: "coagulation", definition: "change to a thick and solid state" },
  { word: "inclined", definition: "directing the mind in a certain direction" },
  { word: "defer", definition: "postpone give way (to show respect)" },
  { word: "infuriate", definition: "fill with fury or rage" },
  { word: "trickle", definition: "flow in drops" },
  { word: "tyro", definition: "tiro beginner" },
  { word: "exculpate", definition: "to clear from a charge of guilt" },
  { word: "impediment", definition: "smth that hinders (e.g. stammer)" },
  { word: "eulogy", definition: "formal praise panegyric" },
  { word: "recant", definition: "take back as being FALSE give up" },
  { word: "ostensible", definition: "seeming appearing as such professed" },
  { word: "pedantic", definition: "bookish showing off learning" },
  { word: "tassel", definition: "bunch of threads" },
  { word: "quixotic", definition: "generous unselfish" },
  { word: "taciturn", definition: "untalkative silent" },
  { word: "sophisticated", definition: "complex subtle refined" },
  { word: "phlegmatic", definition: "calm sluggish temperament unemotional" },
  { word: "counterfeit", definition: "forgery" },
  { word: "recuperate", definition: "become strong after illness loss exhaustion" },
  { word: "heresy", definition: "belief contrary to what is generally accepted" },
  { word: "gloat", definition: "over look at with selfish delight" },
  { word: "fetter", definition: "to shackle put in chains" },
  { word: "subsume", definition: "include under a rule" },
  { word: "revere", definition: "have deep respect for" },
  { word: "fragrant", definition: "sweet-smelling" },
  { word: "foment", definition: "put smth warm (to lessen the pain)" },
  { word: "constrict", definition: "make tight or smaller" },
  { word: "incumbents", definition: "official duties" },
  { word: "spear", definition: "weapon with a metal point on a long shaft" },
  { word: "encomium", definition: "warm or glowing praise eulogy panegyric" },
  { word: "nadir", definition: "lowest weakest point" },
  { word: "covert", definition: "disguised" },
  { word: "recondite", definition: "little known abstruse" },
  { word: "peremptory", definition: "urgent imperative unchallengeable ending debate" },
  { word: "stingy", definition: "spending using unwillingly" },
  { word: "candid", definition: "frank straight-forward" },
  { word: "conjoin", definition: "to join together" },
  { word: "dearth", definition: "shortage" },
  { word: "ulterior", definition: "situated beyond" },
  { word: "figurehead", definition: "carved image on the prow of a ship" },
  { word: "venal", definition: "ready to do smth dishonest" },
  { word: "misogynist", definition: "one who hates women/females" },
  { word: "conceal", definition: "hide keep secret" },
  { word: "decry", definition: "disapprove of" },
  { word: "assuage", definition: "make smth (pain desire) less" },
  { word: "baleful", definition: "harmful ominous causing evil" },
  { word: "malevolence", definition: "wishing to do evil" },
  { word: "paucity", definition: "scarcity a lacking of" },
  { word: "ail", definition: "trouble be ill" },
  { word: "apostate", definition: "one who abandons long-held religious or political convictions" },
  { word: "mundane", definition: "worldly as opposed to spiritual commonplace everyday" },
  { word: "lope", definition: "move along with long strides" },
  { word: "sanctimony", definition: "self-righteousness hypocritical with FALSE piety" },
  { word: "sophomoric", definition: "self-assured though immature affected bombastic overblown" },
  { word: "nostrum", definition: "a quack remedy an untested cure" },
  { word: "prudence", definition: "careful forethought" },
  { word: "bask", definition: "in enjoy warmth and light" },
  { word: "berate", definition: "scold sharply" },
  { word: "fatuous", definition: "without sense foolish self-satisfaction" },
  { word: "grovel", definition: "crawl humble oneself" },
  { word: "voluble", definition: "fluent" },
  { word: "cantankerous", definition: "bad-tempered/quarrelsome" },
  { word: "defiance", definition: "open disobedience or resistance" },
  { word: "wean", definition: "to turn away (from a habit)" },
  { word: "raconteur", definition: "person who tells anecdotes" },
  { word: "forswear", definition: "renounce disallow repudiate" },
  { word: "ignominious", definition: "shameful dishonorable undignified disgraceful" },
  { word: "perfunctory", definition: "done as a duty without care" },
  { word: "peripatetic", definition: "wandering" },
  { word: "smolder", definition: "burn slowly without flame" },
  { word: "pitfall", definition: "covered hole as a trap unsuspected danger" },
  { word: "exploit", definition: "brilliant achievement develop use selfishly" },
  { word: "enunciate", definition: "pronounce (words)/express a theory" },
  { word: "suborn", definition: "induce by bribery or smth to commit perjury" },
  { word: "fallacious", definition: "based on error" },
  { word: "bolster", definition: "give greatly needed support" },
  { word: "snare", definition: "trap" },
  { word: "prolix", definition: "tiring because too long" },
  { word: "sting", definition: "smth sharp" },
  { word: "talon", definition: "claw of a bird of prey" },
  { word: "loll", definition: "rest to sit or stand in a lazy way hang (dog's tongue)" },
  { word: "refine", definition: "make or become pure cultural" },
  { word: "hoodwink", definition: "trick mislead" },
  { word: "levity", definition: "lack of seriousness" },
  { word: "conciliatory", definition: "reconciling soothing comforting mollifying" },
  { word: "preclude", definition: "prevent make impossible" },
  { word: "belabor", definition: "beat hard" },
  { word: "platitude", definition: "a trite or banal statement unoriginality" },
  { word: "husk", definition: "worthless outside part of anything" },
  { word: "mesmerize", definition: "hypnotize" },
  { word: "procrastination", definition: "keeping on putting off" },
  { word: "portent", definition: "omen marvelous threatening" },
  { word: "pest", definition: "destructive thing or a person who is nuisance" },
  { word: "wince", definition: "show bodily or mental pain" },
  { word: "opaqueness", definition: "dullness/not allowing light to pass through" },
  { word: "illicit", definition: "unlawful forbidden" },
  { word: "inundate", definition: "flood cover by overflowing" },
  { word: "palpability", definition: "can be felt touched understood" },
  { word: "paean", definition: "song of praise or triumph" },
  { word: "shun", definition: "keep away from avoid" },
  { word: "perfidious", definition: "treacherous faithless" },
  { word: "reconcile", definition: "settle a quarrel restore peace" },
  { word: "mischievous", definition: "harmful causing mischief" },
  { word: "suffice", definition: "be enough" },
  { word: "chauvinist", definition: "a blindly devoted patriot" },
  { word: "stygian", definition: "hence dark gloomy" },
  { word: "ensign", definition: "flag/badge" },
  { word: "inveigh", definition: "to attack verbally denounce deprecate" },
  { word: "prevaricate", definition: "to equivocate to stray from the truth" },
  { word: "dismal", definition: "sad gloomy miserable" },
  { word: "petrous", definition: "like a rock hard stony" },
  { word: "gullible", definition: "easily gulled" },
  { word: "aplomb", definition: "self-confidence" },
  { word: "stride", definition: "walk with long steps" },
  { word: "accolade", definition: "praise approval" },
  { word: "finesse", definition: "delicate way of dealing with a situation" },
  { word: "contemn", definition: "to scorn or despise" },
  { word: "raffish", definition: "low vulgar base tawdry" },
  { word: "glib", definition: "ready and smooth but not sincere" },
  { word: "dexterity", definition: "skill (esp. in handling)" },
  { word: "grandiloquent", definition: "using pompous words" },
  { word: "glean", definition: "gather facts in small quantities" },
  { word: "grievous", definition: "causing grief or pain serious dire grave" },
  { word: "heinous", definition: "odious (of crime)" },
  { word: "credulous", definition: "ready to believe things" },
  { word: "occluded", definition: "blocked up" },
  { word: "fulmination", definition: "bitter protest" },
  { word: "equanimity", definition: "calmness of temperament" },
  { word: "commodious", definition: "having plenty of space for what is needed" },
  { word: "penury", definition: "extreme poverty" },
  { word: "sash", definition: "long strip worn round the waist" },
  { word: "ebullient", definition: "overflowing with enthusiasm showing excitement" },
  { word: "sophistry", definition: "fallacious reasoning faulty logic" },
  { word: "endemic", definition: "epidemic" },
  { word: "strut", definition: "a supporting bar" },
  { word: "churl", definition: "bad-tempered person" },
  { word: "slake", definition: "to assuage to satisfy allay" },
  { word: "fluster", definition: "make nervous or confused" },
  { word: "concord", definition: "agreement or harmony" },
  { word: "dereliction", definition: "deserting and leaving to fall into ruins" },
  { word: "garner", definition: "to gather and save to store up" },
  { word: "conspicuous", definition: "easily seen remarkable" },
  { word: "gossamer", definition: "soft light delicate material" },
  { word: "impute", definition: "to attribute to a cause or source ascribe" },
  { word: "preternatural", definition: "not normal or usual" },
  { word: "apprehensive", definition: "grasping understanding fear unhappy feeling about future" },
  { word: "latent", definition: "present but not yet active developed or visible" },
  { word: "jocular", definition: "meant as a joke" },
  { word: "timorous", definition: "fearful timid afraid" },
  { word: "centurion", definition: "leader of a unit of 100 soldiers" },
  { word: "foolproof", definition: "incapable of failure or error" },
  { word: "flinch", definition: "draw move back wince" },
  { word: "complaisance", definition: "tending to comply obliging willingness to please" },
  { word: "forge", definition: "workshop for the shaping of metal to shape metal lead" },
  { word: "importune", definition: "beg urgently solicit (of a prostitute)" },
  { word: "rave", definition: "act with excessive enthusiasm" },
  { word: "brazen", definition: "made of brass" },
  { word: "flax", definition: "pale yellow (hair) a plant" },
  { word: "consternation", definition: "surprise and fear dismay" },
  { word: "unencumbered", definition: "easy-going trifle" },
  { word: "arduous", definition: "steep difficult ascent laborious" },
  { word: "scribble", definition: "write hastily" },
  { word: "plummet", definition: "fall plunge steeply" },
  { word: "inchoate", definition: "not yet fully formed rudimentary elementary" },
  { word: "bellicose", definition: "belligerent pugnacious warlike" },
  { word: "temperate", definition: "showing self-control" },
  { word: "turmoil", definition: "trouble disturbance" },
  { word: "mendacity", definition: "dishonesty" },
  { word: "deviance", definition: "being different in moral standards (from normal)" },
  { word: "clot", definition: "half-solid lump formed from liquid" },
  { word: "hallow", definition: "to make holy consecrate" },
  { word: "conviction", definition: "convincing firm belief" },
  { word: "impudent", definition: "rash indiscreet" },
  { word: "sumptuous", definition: "magnificent" },
  { word: "pellucid", definition: "transparent easy to understand" },
  { word: "quack", definition: "person dishonestly claiming to smth" },
  { word: "ineptitude", definition: "quality of being unskillful" },
  { word: "egress", definition: "way out exit" },
  { word: "soporific", definition: "producing sleep" },
  { word: "reactionary", definition: "opposing progress" },
  { word: "soar", definition: "rise fly high" },
  { word: "obtuse", definition: "blunt/stupid" },
  { word: "cabal", definition: "a scheme or plot a group of plotters" },
  { word: "pliant", definition: "pliable easily bent shaped or twisted" },
  { word: "ponderous", definition: "heavy bulky dull" },
  { word: "cloture", definition: "closing device (in Parliament) to end a debate by voting" },
  { word: "halcyon", definition: "calm and peaceful" },
  { word: "acclaimed", definition: "welcomed with shouts and approval" },
  { word: "putrefaction", definition: "becoming rotten" },
  { word: "molt", definition: "moult lose hair feathers before new growing" },
  { word: "viscous", definition: "sticky/semi-fluid" },
  { word: "luminary", definition: "star light-giving body" },
  { word: "impetuous", definition: "having sudden energy impulsive thrusting ahead forceful" },
  { word: "adamant", definition: "kind of stone inflexible" },
  { word: "sagacious", definition: "having sound judgment perceptive wise like a sage" },
  { word: "equable", definition: "steady regular" },
  { word: "superfluous", definition: "more then is needed or wanted" },
  { word: "prudish", definition: "easily shocked excessively modest" },
  { word: "ebullience", definition: "exuberance outburst of feeling" },
  { word: "mendicant", definition: "a beggar" },
  { word: "steeply", definition: "rising or falling sharply" },
  { word: "saturnine", definition: "gloomy dark sullen morose" },
  { word: "hermetic", definition: "sealed by fusion" },
  { word: "astute", definition: "clever quick at seeing to get an advantage" },
  { word: "pivotal", definition: "of great importance (others depend on it)" },
  { word: "flop", definition: "fail/move/fall clumsily" },
  { word: "antithetical", definition: "direct opposing" },
  { word: "peregrination", definition: "traveling about wandering" },
  { word: "esoteric", definition: "abstruse intended only for a small circle of" },
  { word: "indigenous", definition: "native" },
  { word: "equivocal", definition: "having a double or doubtful meaning suspicious" },
  { word: "upbraid", definition: "scold reproach" },
  { word: "condense", definition: "increase in density strength make laconic" },
  { word: "pluck", definition: "pull the feathers off pick (e.g.. flowers)" },
  { word: "concur", definition: "agree in opinion happen together" },
  { word: "aloof", definition: "reserved indifferent" },
  { word: "convoke", definition: "call together summon" },
  { word: "disallow", definition: "refuse to allow or accept as a correct" },
  { word: "gouge", definition: "tool for cutting grooves in wood" },
  { word: "trepidation", definition: "alarm excited state of mind" },
  { word: "pine", definition: "waste away through sorrow or illness" },
  { word: "dynamo", definition: "a generator something that produces electric current" },
  { word: "hew", definition: "make by hard work cut (by striking)" },
  { word: "prim", definition: "neat formal" },
  { word: "provident", definition: "frugal looking to the future" },
  { word: "streak", definition: "long thin move very fast" },
  { word: "intrepid", definition: "fearless brave undaunted" },
  { word: "incessant", definition: "often repeated continual" },
  { word: "pungency", definition: "sharpness stinging quality" },
  { word: "woo", definition: "try to win" },
  { word: "hone", definition: "stone used for sharpening tools" },
  { word: "visceral", definition: "of the internal organs of the body" },
  { word: "inane", definition: "silly senseless" },
  { word: "superimpose", definition: "put smth on the top" },
  { word: "indulgent", definition: "inclined to indulge" },
  { word: "entice", definition: "tempt or persuade" },
  { word: "inured", definition: "accustomed to adapted" },
  { word: "penurious", definition: "poor/stingy" },
  { word: "rift", definition: "split crack dissension" },
  { word: "erudite", definition: "learned scholarly" },
  { word: "truculence", definition: "aggressiveness ferocity" },
  { word: "timid", definition: "shy easily frightened" },
  { word: "desuetude", definition: "cessation of use disuse" },
  { word: "exigency", definition: "emergency an urgent situation" },
  { word: "adulteration", definition: "making unpure poorer in quality" },
  { word: "synopsis", definition: "summary or outline" },
  { word: "drowsiness", definition: "feeling sleepy half asleep" },
  { word: "mince", definition: "pronounce or speak affectedly euphemize" },
  { word: "engrave", definition: "impress deeply" },
  { word: "approbation", definition: "approval" },
  { word: "harrow", definition: "to distress create stress or torment" },
  { word: "obtain", definition: "to be established accepted or customary" },
  { word: "verve", definition: "spirit vigor enthusiasm" },
  { word: "bigot", definition: "stubborn narrow-minded person" },
  { word: "dupe", definition: "cheat make a fool of" },
  { word: "reticent", definition: "reserved untalkative silent taciturn" },
  { word: "prevalent", definition: "common" },
  { word: "coerce", definition: "compel to force to make obedient" },
  { word: "renowned", definition: "celebrated famous" },
  { word: "savant", definition: "person of great learning" },
  { word: "divestiture", definition: "taking off getting rid of giving up" },
  { word: "aver", definition: "affirm assert prove justify" },
  { word: "predominate", definition: "have more power than others" },
  { word: "macerate", definition: "make or become soft by soaking in water" },
  { word: "ameliorate", definition: "improve make better" },
  { word: "turbid", definition: "muddy having the sediment stirred up" },
  { word: "extol", definition: "praise highly" },
  { word: "ingest", definition: "take in by swallowing" },
  { word: "skiff", definition: "small boat" },
  { word: "epicurean", definition: "devoted to pleasure (sensuous enjoyment)" },
  { word: "grave", definition: "serious requiring consideration" },
  { word: "hoax", definition: "mischievous trick played on smb for a joke" },
  { word: "blandness", definition: "polite manner comforting uninteresting" },
  { word: "argot", definition: "jargon slang" },
  { word: "repulsive", definition: "causing a feeling of disgust" },
  { word: "gregarious", definition: "living in societies liking the company" },
  { word: "alcove", definition: "recess/partially enclosed place" },
  { word: "jibe", definition: "gibe make fun of" },
  { word: "repine", definition: "at be discontented with" },
  { word: "disinter", definition: "dig up from the earth" },
  { word: "onerous", definition: "needing effort burdensome" },
  { word: "constrain", definition: "compel" },
  { word: "lithe", definition: "bending twisting" },
  { word: "crease", definition: "line made by crushing white line on the ground in cricket" },
  { word: "eloquence", definition: "fluent speaking skillful use of language" },
  { word: "transient", definition: "temporary fleeting" },
  { word: "stigma", definition: "mark of shame or disgrace" },
  { word: "barren", definition: "not good enough unable to have young ones without value" },
  { word: "highbrow", definition: "(person) with superior tastes" },
  { word: "imperious", definition: "commanding haughty arrogant" },
  { word: "tamp", definition: "tap or drive down by repeated light blows" },
  { word: "temperance", definition: "abstinence from alcohol self-control moderation" },
  { word: "buoyant", definition: "able to float light-hearted" },
  { word: "divulge", definition: "make known smth secret" },
  { word: "pristine", definition: "primitive unspoiled pure as in earlier times unadulterated" },
  { word: "quirk", definition: "habit or action peculiar to smb or smth" },
  { word: "obdurate", definition: "hardened and unrepenting stubborn inflexible" },
  { word: "assail", definition: "with attack violently" },
  { word: "repast", definition: "meal" },
  { word: "torque", definition: "twisting force causing rotation" },
  { word: "eschew", definition: "avoid" },
  { word: "burnish", definition: "to polish rub to a shine" },
  { word: "deplete", definition: "use until none remains" },
  { word: "sundry", definition: "various miscellaneous separate" },
  { word: "subpoena", definition: "written order requiring a person to appear in a low court" },
  { word: "incipient", definition: "beginning" },
  { word: "undermine", definition: "weaken gradually at the base make smth under" },
  { word: "teetotal", definition: "oppose to alcohol" },
  { word: "florid", definition: "very much ornamented naturally red (e.g.. of face)" },
  { word: "abacus", definition: "frame with balls for calculating" },
  { word: "feint", definition: "pretend" },
  { word: "breach", definition: "opening broken place breaking" },
  { word: "interdict", definition: "prohibit forbid" },
  { word: "disseminate", definition: "distribute (esp. ideas)" },
  { word: "rant", definition: "use extravagant language" },
  { word: "benevolence", definition: "wish or activity in doing good" },
  { word: "commuter", definition: "person who travels regularly" },
  { word: "pundit", definition: "pedant authority on a subject" },
  { word: "surcharge", definition: "additional load/charge" },
  { word: "pucker", definition: "wrinkle" },
  { word: "fawn", definition: "young deer try to win smb's favor" },
  { word: "vain", definition: "without use result conceited" },
  { word: "unearth", definition: "discover and bring to light" },
  { word: "corporeal", definition: "physical of or for the body" },
  { word: "liberality", definition: "free giving generosity" },
  { word: "sententious", definition: "short and pithy full of maxims/proverbs" },
  { word: "glimmer", definition: "weak/unsteady light" },
  { word: "facetious", definition: "humorous funny jocular" },
  { word: "inasmuch", definition: "since because" },
  { word: "scent", definition: "smell (esp pleasant)" },
  { word: "implicate", definition: "show that smb has a share" },
  { word: "appease", definition: "make quiet or calm" },
  { word: "disconcert", definition: "upset the self-possession of" },
  { word: "apartheid", definition: "brutal racial discrimination" },
  { word: "obloquy", definition: "abusively detractive language sharp criticism vituperation" },
  { word: "perilous", definition: "dangerous" },
  { word: "hubris", definition: "arrogant pride" },
  { word: "vagary", definition: "strange act or idea" },
  { word: "flak", definition: "criticism/anti-aircraft guns" },
  { word: "gist", definition: "the point general sense" },
  { word: "ferret", definition: "discover by searching search" },
  { word: "contumacious", definition: "insubordinate rebellious" },
  { word: "probity", definition: "uprightness incorruptibility principle" },
  { word: "irrevocable", definition: "final and unalterable" },
  { word: "moderation", definition: "quality of being limited not extreme" },
  { word: "precursory", definition: "preliminary anticipating" },
  { word: "extort", definition: "obtain by threats violence" },
  { word: "hack", definition: "cut roughly hired horse" },
  { word: "froward", definition: "intractable not willing to yield or comply stubborn" },
  { word: "ramify", definition: "to be divided or subdivided to branch out" },
  { word: "rarefy", definition: "to make thin to make less dense to purify or refine" },
  { word: "cravat", definition: "piece of linen worn as a necktie" },
  { word: "irate", definition: "angry" },
  { word: "rivet", definition: "fix take up secure metal pin" },
  { word: "garrulity", definition: "talkativeness" },
  { word: "anguish", definition: "severe suffering" },
  { word: "demagogue", definition: "person appealing not to reasons" },
  { word: "shunt", definition: "send from one track to another lay aside evade discussion" },
  { word: "profuse", definition: "abundant/lavish" },
  { word: "coda", definition: "passage that completes a piece of music" },
  { word: "pique", definition: "hurt the pride or self-respect stir (curiosity)" },
  { word: "heed", definition: "attention/give notice to" },
  { word: "nonplused", definition: "greatly surprised" },
  { word: "evoke", definition: "call up bring out" },
  { word: "decorum", definition: "propriety properness" },
  { word: "epithet", definition: "adjective" },
  { word: "coeval", definition: "of the same period coexisting" },
  { word: "gainsay", definition: "to deny to oppose" },
  { word: "pernicious", definition: "harmful injurious" },
  { word: "miser", definition: "person who loves wealth and spends little" },
  { word: "combustion", definition: "process of burning" },
  { word: "sedulous", definition: "persevering" },
  { word: "vituperate", definition: "curse abuse in words" },
  { word: "inimitable", definition: "defying imitation unmatchable" },
  { word: "squalid", definition: "foul filthy" },
  { word: "enthral", definition: "please greatly/enslave (fig)" },
  { word: "plunge", definition: "move quickly suddenly and with force" },
  { word: "extenuate", definition: "reduce the strength of lessen seriousness partially excuse" },
  { word: "atonement", definition: "repayment death of Jesus" },
  { word: "splice", definition: "join (two ends)" },
  { word: "shallow", definition: "little depth not earnest" },
  { word: "penitent", definition: "feeling or showing regret" },
  { word: "canvass", definition: "discuss thoroughly sort of touting" },
  { word: "middling", definition: "fairly good but not very good" },
  { word: "volubility", definition: "fluency verbosity easy use of spoken language" },
  { word: "terse", definition: "brief and to the point" },
  { word: "predilection", definition: "special liking mental preference" },
  { word: "insouciant", definition: "unconcerned carefree" },
  { word: "gaucherie", definition: "socially awkward tactless behavior" },
  { word: "encapsulate", definition: "enclose in capsule" },
  { word: "taut", definition: "tightly stretched" },
  { word: "consume", definition: "get to the end of" },
  { word: "soot", definition: "black powder in smoke" },
  { word: "dulcet", definition: "melodious harmonious" },
  { word: "involute", definition: "complex" },
  { word: "drone", definition: "male bee person who isn't self-employed" },
  { word: "incorrigibility", definition: "cannot be cured or corrected" },
  { word: "abrogate", definition: "repeal or annul by authority" },
  { word: "ineluctable", definition: "certain inevitable" },
  { word: "imperturbable", definition: "calm not capable of being excited" },
  { word: "cogent", definition: "strong convincing" },
  { word: "discern", definition: "see with an effort but clearly" },
  { word: "discomfit", definition: "confuse embarrass" },
  { word: "petulant", definition: "unreasonably impatient" },
  { word: "veracity", definition: "truth" },
  { word: "swerve", definition: "change direction suddenly" },
  { word: "agile", definition: "active quick-moving" },
  { word: "personable", definition: "pleasing in appearance attractive" },
  { word: "curtail", definition: "make shorter then was planned" },
  { word: "underbid", definition: "make a lower bid then smb else" },
  { word: "asterisk", definition: "the mark * (e.g.. omitted letters)" },
  { word: "recitals", definition: "a number of performance of music" },
  { word: "palate", definition: "roof of the mouth sense of taste" },
  { word: "guile", definition: "deceit cunning" },
  { word: "condone", definition: "forgive" },
  { word: "drawl", definition: "slow way of speaking" },
  { word: "quiescent", definition: "at rest dormant torpid" },
  { word: "sere", definition: "make hard and without feeling" },
  { word: "disencumber", definition: "free from encumbrance" },
  { word: "uncouth", definition: "rough awkward" },
  { word: "assiduous", definition: "diligent hard-working sedulous" },
  { word: "quibble", definition: "try to avoid by sophistication" },
  { word: "ineffable", definition: "to great to be described in words" },
  { word: "glut", definition: "supply to much fill to excess" },
  { word: "resuscitation", definition: "coming back to consciousness" },
  { word: "crush", definition: "press lose shape subdue overwhelm" },
  { word: "overhaul", definition: "examine thoroughly to learn about the condition" },
  { word: "veritable", definition: "real rightly named" },
  { word: "inimical", definition: "harmful or friendly" },
  { word: "barrage", definition: "artificial obstacle built across a river" },
  { word: "ferocity", definition: "savage cruelty" },
  { word: "provoke", definition: "make angry vax" },
  { word: "extricable", definition: "that can be freed" },
  { word: "tenacity", definition: "firmness persistency adhesiveness tending to hang on" },
  { word: "puissance", definition: "strength" },
  { word: "endearing", definition: "making dear or liked" },
  { word: "engrossing", definition: "taken up all the time or attention writing in large or formal" },
  { word: "indolence", definition: "laziness" },
  { word: "gnaw", definition: "waste away bite steadily" },
  { word: "indulge", definition: "gratify give way to satisfy allow oneself" },
  { word: "insinuate", definition: "suggest unpleasantly make a way for smth gently" },
  { word: "sordid", definition: "wretched comfortless contemptible" },
  { word: "calipers", definition: "metal supports attached to the legs measuring instrument" },
  { word: "invective", definition: "abusive language curses" },
  { word: "plaintive", definition: "mournful melancholy sorrowful" },
  { word: "macabre", definition: "gruesome suggesting death" },
  { word: "oblivious", definition: "unaware having no memory" },
  { word: "bogus", definition: "sham counterfeit not genuine" },
  { word: "nascent", definition: "coming into existence emerging" },
  { word: "epitome", definition: "brief summary representative example a typical model" },
  { word: "verdant", definition: "fresh and green" },
  { word: "detumescence", definition: "diminishing or lessening of swelling" },
  { word: "colander", definition: "bowl-shaped vessel with many holes used to drain off water" },
  { word: "rotund", definition: "rich and deep plump and round" },
  { word: "warrant", definition: "authority written order guarantee" },
  { word: "wend", definition: "to go proceed" },
  { word: "stray", definition: "wander lose one's way" },
  { word: "sluggard", definition: "lazy slow-moving person" },
  { word: "incursion", definition: "a raid a sudden attack" },
  { word: "introspection", definition: "examining one's own thoughts and feelings" },
  { word: "equipoise", definition: "equal distribution of weight equilibrium" },
  { word: "scorch", definition: "become discolored/dry up/go at high speed" },
  { word: "hirsute", definition: "hairy shaggy" },
  { word: "gush", definition: "burst out suddenly/talk ardently" },
  { word: "chary", definition: "cautious wary" },
  { word: "repudiate", definition: "disown refuse to accept or pay" },
  { word: "dissolution", definition: "disintegration looseness in morals" },
  { word: "punctilious", definition: "precise paying attention to trivialities" },
  { word: "endorse", definition: "write one's name on the back of" },
  { word: "foil", definition: "prevent from carrying out contrast" },
  { word: "indomitable", definition: "not easily discouraged or subdued" },
  { word: "excoriation", definition: "severe criticism" },
  { word: "conceit", definition: "over-high opinion of too much pride" },
  { word: "neophyte", definition: "person who has been converted to a belief" },
  { word: "demur", definition: "to hesitate raise objections" },
  { word: "multifarious", definition: "varied motley greatly diversified" },
  { word: "ardor", definition: "enthusiasm" },
  { word: "hypocrisy", definition: "falsely making oneself appear to be good" },
  { word: "salubrious", definition: "healthful" },
  { word: "brash", definition: "hasty rush cheeky saucy" },
  { word: "frenetic", definition: "frantic frenzied" },
  { word: "serrated", definition: "having a toothed edge" },
  { word: "pusillanimous", definition: "cowardly craven" },
  { word: "malign", definition: "injurious speak ill of smb tell lie" },
  { word: "ascend", definition: "go or come up" },
  { word: "innocuous", definition: "causing no harm" },
  { word: "falter", definition: "waver/move in an uncertain manner" },
  { word: "sobriety", definition: "quality or condition of being sober" },
  { word: "eddy", definition: "circular or spiral movement (e.g.. of wind)" },
  { word: "clamor", definition: "shout complain with a lot of noise" },
  { word: "fetid", definition: "stinking" },
  { word: "cordial", definition: "warm and sincere" },
  { word: "nibble", definition: "show some inclination to accept (an offer)" },
  { word: "prone", definition: "prostrate inclined to (undesirable things)" },
  { word: "extant", definition: "still in existence" },
  { word: "malleable", definition: "yielding easily shaped moldable adapting" },
  { word: "succor", definition: "assistance relief in time of distress" },
  { word: "render", definition: "deliver provide represent" },
  { word: "obtrusive", definition: "projecting prominent undesirably noticeable" },
  { word: "vigilant", definition: "member of a vigilance committee" },
  { word: "supercilious", definition: "disdainful characterized by haughty scorn" },
  { word: "expostulate", definition: "argue earnestly to dissuade correct or protest" },
  { word: "scurvy", definition: "mean contemptible" },
  { word: "augury", definition: "omen sign" },
  { word: "irksome", definition: "tiresome" },
  { word: "profundity", definition: "depth" },
  { word: "thwart", definition: "obstruct/frustrate" },
  { word: "matriculation", definition: "be admitted enter a university as a student" },
  { word: "rabble", definition: "mob crowd the lower classes of populace" },
  { word: "rebuff", definition: "snub" },
  { word: "foppish", definition: "like a man who pays too much attention to his clothes" },
  { word: "supine", definition: "lying on the back slow to act passive" },
  { word: "loquacious", definition: "talkative garrulous" },
  { word: "germane", definition: "relevant pertinent to" },
  { word: "impugned", definition: "challenged to be doubted" },
  { word: "evince", definition: "to show clearly to indicate" },
  { word: "placate", definition: "soothe pacify calm" },
  { word: "prodigious", definition: "enormous wonderful" },
  { word: "stanch", definition: "to stop the flow of a fluid" },
  { word: "stipulate", definition: "state or put forward as a necessary condition" },
  { word: "elaborate", definition: "worked out with much care in great detail" },
  { word: "weigh", definition: "measure hoe heavy smth is" },
  { word: "diaphanous", definition: "transparent gauzy" },
  { word: "malinger", definition: "to fake illness or injury in order to shirk a duty" },
  { word: "maul", definition: "hurt by rough handling" },
  { word: "stipple", definition: "paint with dots" },
  { word: "fluke", definition: "lucky stroke" },
  { word: "ambidextrous", definition: "able to use the left hand or the right equally well" },
  { word: "consequential", definition: "pompous self important" },
  { word: "poignant", definition: "deeply moving keen" },
  { word: "tenuous", definition: "insubstantial flimsy weak" },
  { word: "morbid", definition: "diseased unhealthy (e.g.. about ideas)" },
  { word: "brass", definition: "yellow metal (mixing copper and zinc)" },
  { word: "perfidy", definition: "treachery breaking of faith" },
  { word: "correlate", definition: "have a mutual relation" },
  { word: "amortize", definition: "end (a debt) by setting aside money" },
  { word: "benign", definition: "kind and gentle mild (climate)" },
  { word: "decree", definition: "order given by authority" },
  { word: "cognizant", definition: "being fully aware of" },
  { word: "sinuous", definition: "winding undulating serpentine" },
  { word: "renovate", definition: "restore smth to better condition" },
  { word: "fragile", definition: "easily injured broken or destroyed" },
  { word: "skit", definition: "short piece of humorous writing" },
  { word: "distraught", definition: "distracted violently upset in mind" },
  { word: "obstreperous", definition: "noisy loud" },
  { word: "truce", definition: "(agreement) stop of fighting for a time" },
  { word: "finicky", definition: "finical" },
  { word: "vigorous", definition: "strong energetic" },
  { word: "connotation", definition: "suggestion in addition to" },
  { word: "clinch", definition: "come to grips/settle conclusively" },
  { word: "effluvia", definition: "outflow in a stream of particles a noxious odor or vapor" },
  { word: "flamboyant", definition: "brightly colored florid" },
  { word: "fledged", definition: "able to fly trained experienced" },
  { word: "beatify", definition: "to bless make happy or ascribe a virtue to" },
  { word: "coddle", definition: "treat with care and tenderness" },
  { word: "chastisement", definition: "punishment" },
  { word: "quotidian", definition: "banal everyday" },
  { word: "implicit", definition: "implied though not plainly expressed" },
  { word: "lassitude", definition: "weariness tiredness" },
  { word: "forbear", definition: "refrain from be patient ancestor" },
  { word: "cursory", definition: "quick hurried" },
  { word: "myriad", definition: "very great number" },
  { word: "impede", definition: "hinder get in the way of" },
  { word: "castigate", definition: "to chastise correct by punishing" },
  { word: "arrogance", definition: "proud superior manner of behaviour" },
  { word: "manacle", definition: "chains for the hands or feet" },
  { word: "recompense", definition: "make payment to reward punish" },
  { word: "aversion", definition: "strong dislike" },
  { word: "noisome", definition: "offensive disgusting (smell)" },
  { word: "morose", definition: "ill-tempered unsocial" },
  { word: "harbinger", definition: "smth or smb that foretells the coming of" },
  { word: "pertain", definition: "belong as a part have reference" },
  { word: "pariah", definition: "an outcast a rejected and despised person" },
  { word: "admonitory", definition: "containing warning" },
  { word: "dubious", definition: "feeling doubt" },
  { word: "haughty", definition: "arrogant conceited" },
  { word: "itinerate", definition: "to travel from place to place to peregrinate" },
  { word: "discredit", definition: "refuse to believe" },
  { word: "graze", definition: "touch or scrape lightly in passing" },
  { word: "disheveled", definition: "untidy" },
  { word: "dormant", definition: "in a state of inactivity but awaiting development" },
  { word: "credulity", definition: "too great a readiness to believe things" },
  { word: "quiescence", definition: "state of being passive/motionless" },
  { word: "doggerel", definition: "trivial poorly constructed verse" },
  { word: "malapropism", definition: "misuse of a word (for one that resembles it)" },
  { word: "secular", definition: "material (not spiritual) living outside monasteries" },
  { word: "denouement", definition: "an outcome or solution the unraveling of a plot" },
  { word: "efficacy", definition: "production of a desired result" },
  { word: "jabber", definition: "talk excitedly utter rapidly" },
  { word: "warmonger", definition: "person who stirs up war" },
  { word: "suppress", definition: "prevent from being known put an end to" },
  { word: "plethora", definition: "glut" },
  { word: "retard", definition: "check hinder" },
  { word: "propitious", definition: "auspicious presenting favorable circumstances" },
  { word: "coax", definition: "get smb to do smth by kindness" },
  { word: "idolatry", definition: "excessive admiration of" },
  { word: "valiant", definition: "brave" },
  { word: "commemorate", definition: "keep the memory of" },
  { word: "verisimilitude", definition: "appearing TRUE or real" },
  { word: "tractable", definition: "easily controlled or guided" },
  { word: "tangential", definition: "suddenly changeable" },
  { word: "effete", definition: "infertile worn out weak" },
  { word: "shrill", definition: "sharp piercing" },
  { word: "cordon", definition: "line (of police acting as a guard)" },
  { word: "impair", definition: "worsen diminish in value" },
  { word: "ingenuous", definition: "naive young artless frank honest sincere" },
  { word: "spurn", definition: "have nothing to do reject or refuse" },
  { word: "desultory", definition: "aimless haphazard digressing at random" },
  { word: "trite", definition: "not new" },
  { word: "implosion", definition: "collapse bursting inward" },
  { word: "enigma", definition: "smth that is puzzling" },
  { word: "boorish", definition: "crude offensive rude" },
  { word: "quell", definition: "suppress subdue" },
  { word: "infuse", definition: "put pour fill" },
  { word: "vivacious", definition: "lively high-spirited" },
  { word: "duress", definition: "threats to compel smb" },
  { word: "fidelity", definition: "loyalty accuracy" },
  { word: "debacle", definition: "a breakup overthrow sudden disaster" },
  { word: "forgery", definition: "counterfeit" },
  { word: "lackluster", definition: "(of eyes) dull" },
  { word: "chicanery", definition: "legal trickery/false argument" },
  { word: "redeem", definition: "get back by payment compensate" },
  { word: "sycophant", definition: "person who flatter to the rich and powerful" },
  { word: "espouse", definition: "marry give one's support to" },
  { word: "fringe", definition: "edge ornamental border part of hair over the forehead" },
  { word: "stickler", definition: "person who insists on importance of smth" },
  { word: "summarily", definition: "briefly without delay" },
  { word: "odor", definition: "smell favor reputation" },
  { word: "hollow", definition: "not soled with hole" },
  { word: "protracted", definition: "prolonged" },
  { word: "recluse", definition: "person who lives alone and avoids people" },
  { word: "incite", definition: "stir up rouse" },
  { word: "holster", definition: "leather case for a pistol" },
  { word: "extempore", definition: "without previous thought or preparation" },
  { word: "lionize", definition: "treat as a famous person" },
  { word: "lien", definition: "legal claim until a debt on it is repaid" },
  { word: "torpid", definition: "sleeping sluggish lethargic dormant" },
  { word: "severance", definition: "severing" },
  { word: "incredulous", definition: "skeptical unwilling to believe" },
  { word: "partisan", definition: "one-sided committed to a party biased or prejudiced" },
  { word: "chastened", definition: "corrected punished" },
  { word: "roll", definition: "call calling of names" },
  { word: "mettlesome", definition: "courageous high-spirited" },
  { word: "supersede", definition: "take the place of" },
  { word: "discreet", definition: "careful/prudent" },
  { word: "sanity", definition: "health of mind soundness of judgement" },
  { word: "enduring", definition: "lasting" },
  { word: "propagation", definition: "increasing the number spreading extending" },
  { word: "permeate", definition: "spread into every part of" },
  { word: "cornucopia", definition: "abundant supply" },
  { word: "regicide", definition: "crime of killing a king" },
  { word: "dainty", definition: "pretty/delicate(food)/difficult to please" },
  { word: "perspicacity", definition: "quick judging and understanding" },
  { word: "indigence", definition: "poverty" },
  { word: "edible", definition: "fit to be eaten/not poisonous" },
  { word: "ominous", definition: "threatening" },
  { word: "exuberance", definition: "state of growing vigorously being full of life" },
  { word: "frantic", definition: "wildly excited with joy pain anxiety" },
  { word: "pry", definition: "get smth inquire too curiously" },
  { word: "forestall", definition: "prevent by taking action in advance preempt" },
  { word: "toady", definition: "obsequious flatterer" },
  { word: "slur", definition: "join sounds/words (indistinct)" },
  { word: "ferment", definition: "substance become excited" },
  { word: "welter", definition: "turmoil a bewildering jumble" },
  { word: "deposition", definition: "dethronement depositing" },
  { word: "implacable", definition: "incapable of being placated unpleasable" },
  { word: "solvent", definition: "of the power of forming a solution" },
  { word: "entangle", definition: "put into difficulties" },
  { word: "legacy", definition: "smth handed down from ancestors" },
  { word: "heterogeneous", definition: "made up of different kinds" },
  { word: "impassive", definition: "unmoved feeling no sign of passion" },
  { word: "fecund", definition: "fertile" },
  { word: "stint", definition: "to be thrifty to set limits" },
  { word: "impiety", definition: "lack of reverence or dutifulness" },
  { word: "desiccant", definition: "substance used to absorb moisture" },
  { word: "coalescing", definition: "coming together and uniting into one substance" },
  { word: "erratic", definition: "irregular in behaviour or opinion" },
  { word: "propitiatory", definition: "conciliatory appeasing mitigating" },
  { word: "hush", definition: "make or become silent" },
  { word: "intransigence", definition: "unwillingness to compromise stubbornness intractability" },
  { word: "reverent", definition: "feeling or showing deep respect" },
  { word: "petrified", definition: "taken away power (to think feel act)" },
  { word: "petrify", definition: "to make hard rocklike" },
  { word: "relapse", definition: "fall back again" },
  { word: "harangue", definition: "a long passionate speech" },
  { word: "seminal", definition: "like a seed constituting a source originative" },
  { word: "surfeit", definition: "satiate feed to fulness or to excess" },
  { word: "impending", definition: "imminent being about to happen expected" },
  { word: "salacious", definition: "obscene" },
  { word: "tepid", definition: "lukewarm" },
  { word: "tamper", definition: "interfere with" },
  { word: "vex", definition: "annoy distress trouble" },
  { word: "cant", definition: "insincere talk/jargon" },
  { word: "apt", definition: "well-suited quick-witted" },
  { word: "unfeigned", definition: "not pretended sincere" },
  { word: "opprobrious", definition: "showing scorn or reproach" },
  { word: "discrete", definition: "individually distinct" },
  { word: "antidote", definition: "medicine used against a poison or a disease" },
  { word: "nonchalant", definition: "not having interest" },
  { word: "rancorous", definition: "feeling bitterness spitefulness" },
  { word: "stentorian", definition: "extremely loud and powerful" },
  { word: "aseptic", definition: "surgically clean" },
  { word: "recalcitrant", definition: "disobedient" },
  { word: "incongruous", definition: "out of place not in harmony or agreement" },
  { word: "crass", definition: "very great (es. stupidity)" },
  { word: "suppliant", definition: "asking humbly beseeching" },
  { word: "quaff", definition: "drink deeply" },
  { word: "connoisseur", definition: "a person with good judgement (e.g.. in art)" },
  { word: "emote", definition: "stir up excite" },
  { word: "caustic", definition: "biting sarcastic" },
  { word: "indelible", definition: "that cannot be rubbed out" },
  { word: "encumbrance", definition: "burden things that get on the way of" },
  { word: "alloy", definition: "to debase by mixing with something inferior" },
  { word: "equivocate", definition: "try to deceive by equivocal language" },
  { word: "descry", definition: "catch sight of see smth in the distance" },
  { word: "countervail", definition: "counterbalance" },
  { word: "subdue", definition: "overcome bring under control" },
  { word: "ascertain", definition: "get to know" },
  { word: "judicious", definition: "sound in judgment wise" },
  { word: "impermeable", definition: "that cannot be permeated" },
  { word: "embellish", definition: "make beautiful" },
  { word: "plead", definition: "address a court of law as an advocate" },
  { word: "broach", definition: "bring up announce begin to talk about" },
  { word: "profligate", definition: "wasteful prodigal licentious extravagant" },
  { word: "deferential", definition: "showing respect" },
  { word: "negligent", definition: "taking too little care" },
  { word: "perpetrate", definition: "be guilty commit (a crime)" },
  { word: "refractory", definition: "stubborn unmanageable untractable" },
  { word: "foible", definition: "defect of character (a person is wrongly proud)" },
  { word: "brittle", definition: "easily broken" },
  { word: "cling", definition: "to resist separation" },
  { word: "tawdry", definition: "cheap gaudy showy tacky" },
  { word: "incense", definition: "make angry" },
  { word: "extirpate", definition: "to destroy exterminate cut out exscind" },
  { word: "forbearance", definition: "patience willingness to wait" },
  { word: "palatial", definition: "magnificent" },
  { word: "satiate", definition: "satisfy fully" },
  { word: "mellifluous", definition: "sweetly flowing" },
  { word: "prune", definition: "dried plum silly person" },
  { word: "dissemble", definition: "speak or behave so as to hide smth (in mind)" },
  { word: "flout", definition: "reject mock to go against (as in going against tradition)" },
  { word: "discountenance", definition: "refuse to approve of" },
  { word: "abysmal", definition: "bottomless extreme" },
  { word: "mercurial", definition: "quick changeable in character fleeting" },
  { word: "disingenuous", definition: "sophisticated artful trying to deceive cunning" },
  { word: "craven", definition: "cowardly" },
  { word: "spurious", definition: "FALSE counterfeit" },
  { word: "travesty", definition: "parody/imitation" },
  { word: "sheath", definition: "cover for the blade of a weapon or a tool" },
  { word: "bequest", definition: "arrangement to give smth at death" },
  { word: "luculent", definition: "easily understood lucid clear" },
  { word: "sequence", definition: "succession connected line of" },
  { word: "curriculum", definition: "course of study" },
  { word: "dogmatic", definition: "positive certain arbitrary without room for discussion" },
  { word: "feckless", definition: "lacking purpose or vitality ineffective careless" },
  { word: "shrewd", definition: "astute showing sound judgement" },
  { word: "taunt", definition: "contemptuous reproach hurtful remark" },
  { word: "vigilance", definition: "watchfulness self-appointed group who maintain order" },
  { word: "alacrity", definition: "eager and cheerful readiness" },
  { word: "mollify", definition: "make calmer or quieter" },
  { word: "impromptu", definition: "without preparation" },
  { word: "obviate", definition: "to make unnecessary get rid of" },
  { word: "austere", definition: "severely moral and strict simple and plain" },
  { word: "aggravate", definition: "make worse irritate" },
  { word: "regale", definition: "to delight or entertain to feast" },
  { word: "repel", definition: "refuse to accept/cause dislike" },
  { word: "rejuvenation", definition: "becoming young in nature or appearance" },
  { word: "recidivism", definition: "relapse into antisocial or criminal behavior" },
  { word: "proliferate", definition: "grow reproduce by rapid multification" },
  { word: "misanthrope", definition: "person who hates mankind" },
  { word: "nexus", definition: "a connection tie or link" },
  { word: "avow", definition: "admit. Declare openly" },
  { word: "servile", definition: "like a slave lacking independence" },
  { word: "asperity", definition: "roughness harshness ill temper irritability" },
  { word: "preponderance", definition: "greatness in number strength weight" },
  { word: "abate", definition: "to lessen to subside" },
  { word: "amalgamate", definition: "mix combine unite societies" },
  { word: "gust", definition: "outburst of feeling sudden rain wind fire etc." },
  { word: "rumple", definition: "make rough" },
  { word: "abstruse", definition: "difficult to comprehend obscure" },
  { word: "curmudgeon", definition: "bad-tempered person" },
  { word: "vestige", definition: "trace or sign" },
  { word: "plod", definition: "continue doing smth without resting" },
  { word: "enmity", definition: "hatred being an enemy" },
  { word: "exhaustive", definition: "complete thorough" },
  { word: "supplicate", definition: "make a humble petition to" },
  { word: "aberration", definition: "straying away from what is normal" },
  { word: "riddle", definition: "puzzling person or thing" },
  { word: "burgeon", definition: "grow forth send out buds" },
  { word: "diffidence", definition: "shyness" },
  { word: "delineate", definition: "to portray depict sketch out" },
  { word: "ostracism", definition: "shut out from society refuse to meet talk" },
  { word: "coy", definition: "shy/modest (esp of a girl)" },
  { word: "limn", definition: "paint portray" },
  { word: "extinct", definition: "no longer active" },
  { word: "meticulous", definition: "giving great attention to details" },
  { word: "trudge", definition: "walk heavily" },
  { word: "patron", definition: "regular customer person who gives support" },
  { word: "transgress", definition: "break go beyond (a limit)" },
  { word: "veer", definition: "change direction" },
  { word: "dwarf", definition: "person or smb much below the usual size" },
  { word: "droll", definition: "jesting" },
  { word: "fervid", definition: "showing earnest feeling" },
  { word: "trifling", definition: "unimportant" },
  { word: "impervious", definition: "not allowing to pass through (of materials)" },
  { word: "arboreal", definition: "of connected with trees" },
  { word: "rapacious", definition: "greedy (esp for money)" },
  { word: "countenance", definition: "to favor or approve of" },
  { word: "disdain", definition: "look on with contempt" },
  { word: "testiness", definition: "witness/evidence" },
  { word: "knit", definition: "draw together unite firmly" },
  { word: "inveterate", definition: "deep-rooted. long-established" },
  { word: "embezzle", definition: "use in a wrong way for one's own benefit" },
  { word: "daunt", definition: "intimidate make fearful" },
  { word: "pinch", definition: "be too tight take between the thumb and finger" },
  { word: "qualm", definition: "feeling of doubt temporary feeling of sickness" },
  { word: "perish", definition: "be destroyed decay" },
  { word: "hoi", definition: "polloi the masses the rabble" },
  { word: "feud", definition: "bitter quarrel over a long period of time" },
  { word: "bewilder", definition: "puzzle confuse" },
  { word: "panegyric", definition: "formal praise eulogy" },
  { word: "diatribe", definition: "bitter and violent attack in words" },
  { word: "denigrate", definition: "blacken belittle sully defame" },
  { word: "clientele", definition: "customers" },
  { word: "sublime", definition: "extreme astounding" },
  { word: "effrontery", definition: "boldness impudence arrogance" },
  { word: "acarpous", definition: "effete no longer fertile worn out" },
  { word: "euphoria", definition: "elation state of pleasant excitement" },
  { word: "tadpole", definition: "form of a frog when it leaves the egg" },
  { word: "exoneration", definition: "set smb clear free (e.g.. from blame)" },
  { word: "idyll", definition: "a carefree episode or experience" },
  { word: "intersperse", definition: "place here and there" },
  { word: "elicit", definition: "draw out" },
  { word: "tonic", definition: "smth giving strength or energy" },
  { word: "tautology", definition: "a repetition a redundancy" },
  { word: "vitiate", definition: "lower the quality weaken the strength" },
  { word: "indistinct", definition: "not easily heard seen clearly marked" },
  { word: "lavish", definition: "giving or producing freely liberally or generously" },
  { word: "pugnacious", definition: "fond of in the habit of fighting" },
  { word: "waft", definition: "scent waving movement carry lightly through" },
  { word: "frugal", definition: "careful economical" },
  { word: "muffler", definition: "cloth worn round the neck/silencer" },
  { word: "abjure", definition: "promise or swear to give up" },
  { word: "philistine", definition: "a smug ignorant person one who lacks knowledge" },
  { word: "propinquity", definition: "nearness in time or place affinity of nature" },
  { word: "pith", definition: "essential part force soft liquid substance" },
  { word: "lumber", definition: "move in a clumsy/noisy way" },
  { word: "garment", definition: "article of clothing" },
  { word: "lachrymose", definition: "causing tears tearful" },
  { word: "indefatigability", definition: "not easily exhaustible tirelessness" },
  { word: "dawdler", definition: "person who is slow waste of time" },
  { word: "parenthesis", definition: "sentence within another one smth separated" },
  { word: "contrite", definition: "filled with deep sorrow for wrongdoing" },
  { word: "garrulous", definition: "too talkative" },
  { word: "blatant", definition: "noisy and rough" },
  { word: "waffle", definition: "talk vaguely and without much result" },
  { word: "arrant", definition: "in the highest degree" },
  { word: "pied", definition: "of mixed colors" },
  { word: "cryptic", definition: "secret with a hidden meaning" },
  { word: "urbane", definition: "elegant refined in manners" },
  { word: "contentious", definition: "argumentative pugnacious combative quarrelsome" },
  { word: "somatic", definition: "of the body" },
  { word: "sawdust", definition: "tiny bits of wood" },
  { word: "balk", definition: "obstacle purposely to get on the way of" },
  { word: "fidget", definition: "move restlessly make nervous" },
  { word: "impecunious", definition: "having little or no money" },
  { word: "obsequious", definition: "too eager to obey or serve" },
  { word: "savor", definition: "taste flavor smth" },
  { word: "equilibrium", definition: "state of being balanced" },
  { word: "cadge", definition: "to beg to get by begging" },
  { word: "resigned", definition: "unresisting submissive" },
  { word: "minatory", definition: "menacing threatening" },
  { word: "imperative", definition: "urgent essential" },
  { word: "gorge", definition: "eat greedily/narrow opening with a stream" },
  { word: "libel", definition: "statement that damages reputation" },
  { word: "lucubrate", definition: "write in scholarly fashion" },
  { word: "ostentation", definition: "display to obtain admiration or envy" },
  { word: "maladroit", definition: "tactless clumsy" },
  { word: "piquant", definition: "agreeably pungent stimulating" },
  { word: "attenuate", definition: "make thin. weaken enervate" },
  { word: "dislodge", definition: "move force from the place occupied" },
  { word: "expurgate", definition: "to remove obscenity purify censor" },
  { word: "affable", definition: "polite and friendly" },
  { word: "sponge", definition: "porous rubber for washing live at once expense" },
  { word: "blithe", definition: "cheerful casual carefree" },
  { word: "vacillation", definition: "being uncertain hesitating" },
  { word: "temerity", definition: "boldness brashness intrepidness" },
  { word: "turquoise", definition: "greenish-blue precious stone" },
  { word: "recreancy", definition: "cowardice a cowardly giving up" },
  { word: "peccadillo", definition: "small sin small weakness in one's character" },
  { word: "discourse", definition: "speech lecture" },
  { word: "abhor", definition: "to hate to detest" },
  { word: "snub", definition: "treat with contempt" },
  { word: "dolt", definition: "stupid fellow" },
  { word: "agog", definition: "eager/excited" },
  { word: "duplicity", definition: "deliberate deception" },
  { word: "machination", definition: "plot scheme (esp. evil)" },
  { word: "recast", definition: "cast or fashion anew" },
  { word: "invincible", definition: "too strong to be defeated" },
  { word: "entreat", definition: "ask earnestly" },
  { word: "writ", definition: "written order" },
  { word: "auxiliary", definition: "helping supporting" },
  { word: "palliate", definition: "lessen the severity of" },
  { word: "quandary", definition: "state of doubt or perplexity" },
  { word: "deluge", definition: "great flood heavy rush of water" },
  { word: "imprecation", definition: "an invocation of evil a curse" },
  { word: "immutable", definition: "that cannot be changed" },
  { word: "ire", definition: "anger" },
  { word: "emaciate", definition: "make thin and weak" },
  { word: "remonstrate", definition: "to protest object" },
  { word: "articulate", definition: "speak distinctly connect by joints" },
  { word: "pious", definition: "dutiful to parents devoted to religion" },
  { word: "accretion", definition: "the growing of separate things into one" },
  { word: "maverick", definition: "rebel nonconformist" },
  { word: "abdication", definition: "giving up control authority" },
  { word: "tortuous", definition: "devious/not straightforward" },
  { word: "enervate", definition: "weaken deprive of strength attenuate" },
  { word: "parsimonious", definition: "too economical miserly" },
  { word: "slate", definition: "king of blue-grey stone propose criticize" },
  { word: "proscribe", definition: "denounce as dangerous" },
  { word: "sever", definition: "break off" },
  { word: "immaculate", definition: "pure faultless" },
  { word: "prodigal", definition: "wasteful reckless with money" },
  { word: "stigmatize", definition: "describe smb scornfully" },
  { word: "animosity", definition: "strong dislike" },
  { word: "labyrinthine", definition: "to entangle the state of affairs" },
  { word: "congeal", definition: "make or become stiff and solid" },
  { word: "corroboration", definition: "additional strengthening evidence" },
  { word: "picaresque", definition: "involving clever rogues or adventurers" },
  { word: "reciprocity", definition: "granting of privileges in return for similar" },
  { word: "irresolute", definition: "hesitating undecided" },
  { word: "paradigm", definition: "a model example or pattern" },
  { word: "baneful", definition: "causing harm or ruin pernicious destructive" },
  { word: "dissent", definition: "have a different opinion refuse to assent" },
  { word: "elegy", definition: "a lament a melancholy composition" },
  { word: "ambiguous", definition: "doubtful uncertain" },
  { word: "serration", definition: "having a toothed edge" },
  { word: "tarnished", definition: "lost brightness" },
  { word: "profligacy", definition: "shameless immorality" },
  { word: "august", definition: "majestic venerable" },
  { word: "apropos", definition: "appropriate to the situation apt" },
  { word: "virago", definition: "a loud domineering woman a scold or nag" },
  { word: "ambivalent", definition: "having both of two contrary meanings" },
  { word: "laudatory", definition: "expressing or giving praise" },
  { word: "compunction", definition: "feeling of regret for one's action" },
  { word: "iconoclast", definition: "person who attacks popular beliefs" },
  { word: "ascribe", definition: "consider to be the origin of or belonging to" },
  { word: "torment", definition: "severe pain or suffering" },
  { word: "massacre", definition: "cruel killing of a large number of people" },
  { word: "forfeit", definition: "suffer the loss of smth" },
  { word: "felon", definition: "person guilty of murder" },
  { word: "fixate", definition: "stare at" },
  { word: "goad", definition: "smth urging a person to action" },
  { word: "abide", definition: "be faithful to endure" },
  { word: "perjury", definition: "willful FALSE statement unlawful act" },
  { word: "eradicate", definition: "get rid of pull up by the roots" },
  { word: "dote", definition: "show much fondness center one's attention" },
  { word: "incise", definition: "engrave make a cut in" },
  { word: "abet", definition: "help/encourage smb (in doing wrong)" },
  { word: "imminent", definition: "likely to come or happen soon" },
  { word: "boisterous", definition: "loud noisy rough lacking restraint" },
  { word: "pedestrian", definition: "commonplace trite unremarkable" },
  { word: "lull", definition: "become quiet or less active" },
  { word: "thrift", definition: "care economy thriving prosperous" },
  { word: "fleet", definition: "number of ships quick-moving" },
  { word: "expatiate", definition: "to roam wander freely" },
  { word: "sodden", definition: "soaked saturated" },
  { word: "unscathed", definition: "unharmed unhurt" },
  { word: "conundrum", definition: "a riddle dilemma enigma" },
  { word: "imbroglio", definition: "complicated and embarrassing situation" },
  { word: "imperviousness", definition: "haughty arrogant commanding" },
  { word: "submerge", definition: "put under water liquid sink out of sight" },
  { word: "veneer", definition: "surface appearance covering the TRUE nature" },
  { word: "finical", definition: "too fussy about food clothing etc." },
  { word: "reproach", definition: "scold upbraid" },
  { word: "provisional", definition: "of the present time only" },
  { word: "vilify", definition: "slander say evil things" },
  { word: "cower", definition: "crouch shrink back" },
  { word: "premature", definition: "doing or happening smth before the right time" },
  { word: "susceptibility", definition: "sensitiveness" }
],
    hm_wordHint         = '',
      
    hm_Letter           = hm_container.find('.hm__letterInput'),
    hm_guessLetter        = hm_container.find('.hm__guessLetter'),
    hm_Word              = hm_container.find('.hm__wordInput'),
    hm_guessWord        = hm_container.find('.hm__guessWord'),
  
    hm_guessContainer       = hm_container.find('.hm__guesses'),
    hm_guessLimit         = 6,
    
    hm_endMessage           = hm_container.find('.hm__gameEndMessage'),
     hm_gameActive        = true
  ;


  /*
    Reusable functions, used frequently the component
  */
  function wrongLetter() {
    hm_guessLimit--;
    hm_guessContainer.text(hm_guessLimit);
  }
  
  function wrongGuess() {
    hm_guessLimit = hm_guessLimit - 2;
    
    if ( hm_guessLimit < 0 ) {
      hm_guessLimit = 0;
    }
    
    hm_guessContainer.text(hm_guessLimit);
  }
  
  function checkGameStatus() {
    
    if ( hm_gameActive === true ) {
    
      var
        totalLetters        = 0,
        remainingLetters      = 0
      ;

      hm_container.find('.hm__letter').each(function(){

        totalLetters++;

        if ( $(this).hasClass('hm__letter--hidden') ) {
          remainingLetters++;
        }
      });
      
      // Give the hint if the person has 1 or 2 guesses left
      if ( hm_guessLimit == 1 || hm_guessLimit == 2 ) {
        $('.hm__hint').text('Hint: ' + hm_wordHint);
      }

      // If the game is lost
      if ( hm_guessLimit == 0 && remainingLetters > 0 ) {
        hm_gameActive = false;

        $('.container-fluid').addClass('hm__gameLost');
        $('.hm__letter').removeClass('hm__letter--hidden');
        hm_endMessage.text('Sorry, you lost!');

      // If the game is won
      } else if ( hm_guessLimit > 0 && remainingLetters == 0 ) {
        hm_gameActive = false;

        $('.container-fluid').addClass('hm__gameWon');
        hm_endMessage.text('Congrats, you won!');

      }
    }
  }
  
  
  // What to do when the page loads
  function init() {
    
    // Find the word to guess
    var
      randomNumber   = Math.round(Math.random() * hm_wordList.length),
      randomWord     = hm_wordList[randomNumber]['word'],
      randomHint     = hm_wordList[randomNumber]['definition']
    ;
    
    hm_word = randomWord;
    hm_wordHint = randomHint;
    hm_wordArray = hm_word.split('');
    
    // Put the starting guess limit in the HTML
    hm_guessContainer.text(hm_guessLimit);
    
    // Add the secret word's HTML to the pen
    for (var i = 0; i < hm_wordArray.length; i++) {
      var hm_letter = '<span class="hm__letter hm__letter--hidden">' + hm_wordArray[i] + '</span>';
      
      hm_wordContainer.append(hm_letter);
    } 
  }

  /*
    Events triggered by the user, mostly click events
  */
  function setEvents() {
    
    hm_guessLetter.on('click', function(){
      
      if ( hm_gameActive === true ) {
      
        var
          guessedLetter     = hm_Letter.val().toLowerCase(),
          correctGuess      = false
        ;

        if ( guessedLetter.length == 1 ) {

          for (var i = 0; i < hm_wordArray.length; i++) {
            var currentLetter = hm_wordArray[i].toLowerCase();

            if (guessedLetter == currentLetter) {
              $('.hm__letter').eq(i).removeClass('hm__letter--hidden');
              correctGuess = true;
            }

            hm_Letter.val('');
          }

        } else if ( guessedLetter.length > 1 ) {
          alert('Please only guess one letter at a time!');
        }

        if ( correctGuess === false ) {
          wrongLetter();
        }

        checkGameStatus();
      }
    });

    hm_guessWord.on('click', function() {
      
      if ( hm_gameActive === true ){

        var
          guessedWord = hm_Word.val().toLowerCase(),
          correctWord = hm_word.toLowerCase()
        ;

        if ( guessedWord == correctWord ) {
          $('.hm__letter').removeClass('hm__letter--hidden');
        } else {
          wrongGuess();
        }

        hm_Word.val('');

        checkGameStatus();
      }
    });
  }

  // Running the initial and event functions for the Super Menu when the page loads
  function docReady() {
    init();
    setEvents();
  }

  $(document).on({
    ready: docReady()
  });
}


// Getting/adding all the super menus and either using its unique ID or adding a custom one
$('.hm__container').each(function(){

  var id = $(this).attr('id');
  
  if ( typeof id === typeof undefined && id !== false ) {
    
    id = 'IDUNIQUE_' + Math.floor((Math.random() * 999999999999) + 1);
    $(this).attr('id', id);
  }
  
  hangman_game(id);
});
